// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcfssnctfnfxojhmuwts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZnNzbmN0Zm5meG9qaG11d3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzg0MDksImV4cCI6MjA2ODc1NDQwOX0.g0kkp4GLuz2VeXDo5Oza1wiWDffNKK5y9t-c5funRhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});